### PR TITLE
✨ NEW: Use external markdown-it plugins

### LINKED ISSUE #5: Add VS Code previewer extension
You can extend the VS Code Markdown previewer, *via* markdown-it plugins: https://code.visualstudio.com/api/extension-guides/markdown-extension

### LINKED ISSUE #18: VSCode Markdown Preview Enhancement: MyST enhancements are not rendering as expected
The Markdown Preview is not correctly rendering the MyST enhancements. 
The following enhanced markdown is ignored and only the content is rendered as plain text.
````
```{tip}
this is a MyST tip that fails!
```
````

The MyST-Markdown extension is enabled since highlighting, intellisense, etc works on the enhanced MyST. However it seems that the enhanced Preview part is either not working or not activated.  None of the enhanced MyST markup is previewing as expected. The config setting is ticked and VSCode has been restarted many times. I have even added   `"myst.preview.enable": true` to my settings.json as a hack but with no effect. Also this same file is correctly rendered by jupyter-book (`jb build/page ...`)

PS. The marketplace advertising blurb  of MyST-Markdown shows this feature working but Issue #5 seems related and is still open?

**Screenshots**

- Screenshot of Extension config in VSCode:extension 
image

- Screenshot of *Edit* and *Preview* panes in VSCode:
image

- Screenshot from browser with MyST rendered as expected
image

**Desktop**
 - Windows 10, and Windows 10 with WSL2 Ubuntu
 - VSCode 1.48.2
 - MyST-Markdown v0.10.2

### LINKED ISSUE #23: Inline roles in tables break markdown preview
**Describe the bug**
Inline roles in pipeline tables seem to cause the preview engine to freeze.

**To Reproduce**

1. Download this file and remove the `.txt` extension. (Github wouldn't let me upload a `.md` file.)
[roles-in-tables-bug.md.txt](https://github.com/executablebooks/myst-language-support/files/6259903/roles-in-tables-bug.md.txt)
2. Open it in VS Code.
3. Run the command `Markdown: Open Preview to the Side`

**Expected behavior**

The contents of the file should be displayed in a markdown preview on the right side.

**Actual behavior:**

If the preview has never been loaded for the file, the preview pane remains blank.
If the preview has been loaded previously for the same file, it stops updating the new content.

**Screenshots**

Here is a screenshot with a table including inline roles, where the preview fails to load.

broken-screenshot

Here is a screenshot of the same file, except without the table that has the inline roles.

working-screenshot

**Desktop**

 - OS: MacOS 11.2.3 (20D91)
 - VS Code:  1.54.3
 - MyST-Markdown: v0.10.2

**Additional context**

Here is the log output in the `Log (Window)`.

```
[2021-04-05 12:31:01.964] [renderer1] [error] Cannot read property 'attrPush' of undefined: TypeError: Cannot read property 'attrPush' of undefined
    at Object.exports.addAttrs (~/.vscode/extensions/jebbs.markdown-extended-1.0.19/node_modules/markdown-it-attrs/utils.js:127:13)
    at Object.transform (~/.vscode/extensions/jebbs.markdown-extended-1.0.19/node_modules/markdown-it-attrs/patterns.js:66:15)
    at Array.curlyAttrs (~/.vscode/extensions/jebbs.markdown-extended-1.0.19/node_modules/markdown-it-attrs/index.js:30:19)
    at a.process (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:142666)
    at h.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:103780)
    at t.MarkdownEngine.tokenizeString (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:97452)
    at t.MarkdownEngine.tokenizeDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:97329)
    at t.MarkdownEngine.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:97850)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at t.default.getRegions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:62771)
    at async Promise.all (index 0)
    at t.default.provideFoldingRanges (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:62620)
```

### LINKED ISSUE #28: Unpin testing from VS Code 1.47.0
In #27 tests were pinned to this version, since there was failures using the latest version.

I should:

- [ ] find the newest version that does still and at least update to that,
- [ ] work out what the actual issue is with the newest version
- [ ] think of the best way to pin to a vscode version, but also point out when this is getting old. Or maybe something like running for a pinned version and runnning for the latest version (but allowing this to fail)

### PR DESCRIPTION
**Pull request by chrisjsewell**
Replaced the (very adhoc) local markdown-it plugin for directives, with https://github.com/executablebooks/markdown-it-docutils, and in general it works 🎉 ! (some notes and todos below)

image

TODOS:

- [x] markdown-it-docutils has not yet implemented `code`/`code-block`/`code-cell` directives; once that is done there will be > parity with the plugin it is replacing
  - I noted that, incorrectly, `{code-block}` does not get parsed as a directive, which needs to be fixed, i.e. the regex needs to include `-` 
- [x] The required markdown-it plugins should be added (i.e. front-matter and footnote)
- [x] The additional myst extensions should be added (dollarmath, amsmath, deflist, ...), and turned on/off via a setting 
- [x] Currently I have just copy/pasted `markdown-it-docutils/dist/css/style.min.css` to `./styles.css`, but it would be good to have this updated automatically
- [x] For some reason the admonition icons are not showing correctly, I also noted this when looking at https://executablebooks.github.io/markdown-it-docutils/ on my mobile (ios)
   - Note this is not the case for Furo itself (where the icons come from), so I must be missing something from there 🤷  
- [ ] when you place a cursor, or highlight some text, in the source text, you can see above that the line it is on is also indicated in the preview. However, for admonitions their styling appears to obstruct it. 
	- Note that it does show up for "indented" components like lists; 
image
    - This also highlights the importance of correctly setting `Token.map` for all the (block) nodes
- [x] Currently the CSS (taken from https://github.com/pradyunsg/furo, see https://github.com/executablebooks/markdown-it-docutils/blob/main/src/style/_variables.scss) uses `@media (prefers-color-scheme: dark)` to change between light and dark themes. This doesn't necessarily play well with the VS Code themes, so should think about either (a) if this is the best approach in the first place and/or (b) if we should override some of these variables.

@rowanc1 it would be great if you give this a try (the dev instructions are in the README); it would be good for you to understand this use case for the markdown-it plugins, and maybe even get some idea for curvenote 😄 

also cc @pradyunsg (as mentioned I borrowed some of your sass from Furo 😄)

### CODE REVIEW

**Comment by rowanc1** [comment]
Just seeing this in the css -- https://caniuse.com/css-masks is not in chrome/webkit which this uses. 

Mine currently look like this in Chrome here: https://executablebooks.github.io/markdown-it-docutils/:
image

(changed the mask property on the second one...)

**Comment by chrisjsewell** [comment]
Ah cheers, that could be it then 👍

**Comment by chrisjsewell** [comment]
Ah so furo uses https://github.com/postcss/autoprefixer (via gulp) during the css compliation, which auto-adds vendor prefixes (which is why I did not find e.g. `-webkit-mask-image` in the actual sass)

**Comment by chrisjsewell** [comment]
After update to markdown-it-docutils v0.0.10:

image

**Comment by adam-grant-hendry** [comment]
Sorry to dig up this old PR. It doesn't look like `{toctree}` directives are supported or properly rendered.

**Pull request merged**
